import { bookImages } from "./bookImages";

// Helper function to calculate original price based on discounted price
// Rounds to nearest value that's 30-80% higher than discounted price
const calculateOriginalPrice = (discountedPrice) => {
  const minMultiplier = 1.3;
  const maxMultiplier = 1.8;
  const randomMultiplier =
    minMultiplier + Math.random() * (maxMultiplier - minMultiplier);
  const calculatedPrice = Math.round(discountedPrice * randomMultiplier);
  // Round to nearest 10 for cleaner pricing
  return Math.round(calculatedPrice / 10) * 10;
};

export const books = [
  {
    id: "bk-001",
    name: "The art of spending money",
    image: bookImages["the-art-of-spending-money"],
    description:
      "A practical guide to building a healthier relationship with money and spending intentionally.",
    catalogue: ["finance", "self-help", "trending", "money-management"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-002",
    name: "Manifest",
    image: bookImages["manifest"],
    description:
      "A mindset-shifting book focused on belief systems and manifestation.",
    catalogue: ["self-help", "trending", "spirituality", "personal-growth"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-003",
    name: "Don't smell the small stuff",
    image: bookImages["dont-sweat-the-small-stuff"],
    description: "Simple practices to reduce stress and live a calmer life.",
    catalogue: ["self-help", "mental-health", "stress-management", "wellness"],
    originalPrice: calculateOriginalPrice(119),
    discountedPrice: 119,
    size: "Paperback",
  },
  {
    id: "bk-004",
    name: "Letter to millennia",
    image: bookImages["letters-to-the-milena"],
    description: "Reflections on modern struggles, ambition, and purpose.",
    catalogue: ["non-fiction", "self-help", "modern-life", "philosophy"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-005",
    name: "Atomic habits",
    image: bookImages["atomic-habits"],
    description: "Build good habits and break bad ones with small changes.",
    catalogue: ["self-improvement", "productivity", "bestseller", "habits"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-006",
    name: "Psychology money",
    image: bookImages["psychology-of-money"],
    description: "Timeless lessons on money, greed, and happiness.",
    catalogue: [
      "finance",
      "psychology",
      "bestseller",
      "money-management",
      "behavioral-economics",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-007",
    name: "Surrounded by idiots",
    image: bookImages["surrounded-by-idiots"],
    description: "Understand personality types and improve communication.",
    catalogue: [
      "psychology",
      "self-help",
      "communication",
      "personality",
      "business",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-008",
    name: "Palace of illusions",
    image: bookImages["palace-of-illusions"],
    description: "A retelling of the Mahabharata from Draupadi's perspective.",
    catalogue: [
      "fiction",
      "novel",
      "mythology",
      "indian-literature",
      "historical-fiction",
    ],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-009",
    name: "Courage to be disliked",
    image: bookImages["courage-to-be-disliked"],
    description: "A philosophy-driven guide to personal freedom.",
    catalogue: [
      "philosophy",
      "self-help",
      "trending",
      "psychology",
      "adlerian",
    ],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-010",
    name: "The subtle art of not giving a f*ck",
    image: bookImages["subtle-art-not-giving-fck"],
    description: "A counterintuitive approach to living a good life.",
    catalogue: [
      "self-help",
      "psychology",
      "bestseller",
      "mindset",
      "life-advice",
    ],
    originalPrice: calculateOriginalPrice(119),
    discountedPrice: 119,
    size: "Paperback",
  },
  {
    id: "bk-011",
    name: "Talking with psychopaths",
    image: bookImages["talking-with-psychopaths"],
    description: "Insights into the minds of psychopaths and their behavior.",
    catalogue: [
      "psychology",
      "true-crime",
      "non-fiction",
      "mental-health",
      "criminology",
    ],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-012",
    name: "Law of human nature",
    image: bookImages["laws-of-human-nature"],
    description: "Understanding the forces that shape human behavior.",
    catalogue: [
      "psychology",
      "self-help",
      "philosophy",
      "sociology",
      "human-behavior",
    ],
    originalPrice: calculateOriginalPrice(239),
    discountedPrice: 239,
    size: "Hardcover",
  },
  {
    id: "bk-013",
    name: "48 laws of power",
    image: bookImages["48-laws-of-power"],
    description: "Classic guide to power dynamics and strategy.",
    catalogue: [
      "self-help",
      "psychology",
      "philosophy",
      "strategy",
      "bestseller",
      "power-dynamics",
    ],
    originalPrice: calculateOriginalPrice(239),
    discountedPrice: 239,
    size: "Hardcover",
  },
  {
    id: "bk-014",
    name: "Diary of a CEO",
    image: bookImages["diary-of-a-ceo"],
    description: "Insights and lessons from a successful CEO's journey.",
    catalogue: [
      "business",
      "entrepreneurship",
      "biography",
      "leadership",
      "self-help",
    ],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-015",
    name: "Red flags and rishtas",
    image: bookImages["red-flags-and-rishtas"],
    description:
      "Navigating modern relationships and identifying warning signs.",
    catalogue: [
      "relationships",
      "self-help",
      "modern-life",
      "dating",
      "contemporary",
    ],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-016",
    name: "Inmate",
    image: bookImages["inmate"],
    description: "A gripping psychological thriller full of twists.",
    catalogue: [
      "thriller",
      "novel",
      "trending",
      "psychological-thriller",
      "mystery",
    ],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-017",
    name: "Housemaid 1",
    image: bookImages["housemaid-1"],
    description: "A dark psychological thriller with shocking revelations.",
    catalogue: [
      "thriller",
      "novel",
      "suspense",
      "psychological-thriller",
      "mystery",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-018",
    name: "Housemaid 2",
    image: bookImages["housemaid-2"],
    description: "The suspense continues with deeper secrets.",
    catalogue: [
      "thriller",
      "novel",
      "suspense",
      "psychological-thriller",
      "mystery",
      "series",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-019",
    name: "Housemaid 3",
    image: bookImages["housemaid-3"],
    description: "A shocking conclusion to the Housemaid series.",
    catalogue: [
      "thriller",
      "novel",
      "suspense",
      "psychological-thriller",
      "mystery",
      "series",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-020",
    name: "Locked door",
    image: bookImages["locked-door"],
    description: "A suspenseful thriller about secrets behind closed doors.",
    catalogue: [
      "thriller",
      "mystery",
      "suspense",
      "crime",
      "psychological-thriller",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-021",
    name: "Never lie",
    image: bookImages["never-lie"],
    description: "A psychological thriller about truth and deception.",
    catalogue: ["thriller", "mystery", "suspense", "psychological", "crime"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-022",
    name: "Days at morisaki shop 1",
    image: bookImages["days-at-morisaki-1"],
    description: "A heartwarming story about life and second chances.",
    catalogue: [
      "fiction",
      "contemporary",
      "slice-of-life",
      "healing",
      "japanese-literature",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-023",
    name: "Days at morisaki shop 2",
    image: bookImages["days-at-morisaki-2"],
    description: "Continuing the heartwarming journey at Morisaki shop.",
    catalogue: [
      "fiction",
      "contemporary",
      "slice-of-life",
      "healing",
      "japanese-literature",
      "series",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-024",
    name: "All he'll be ever",
    image: bookImages["all-hell-ever-be"],
    description: "A deep exploration of relationships and expectations.",
    catalogue: [
      "romance",
      "fiction",
      "relationships",
      "emotional",
      "contemporary",
    ],
    originalPrice: calculateOriginalPrice(229),
    discountedPrice: 229,
    size: "Paperback",
  },
  {
    id: "bk-025",
    name: "Was I ever enough",
    image: bookImages["was-i-ever-enough"],
    description: "A poignant reflection on self-worth and validation.",
    catalogue: ["self-help", "mental-health", "poetry", "emotional", "healing"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-026",
    name: "We are there for each other",
    image: bookImages["we-are-there-for-each-other"],
    description: "A story of friendship, support, and human connection.",
    catalogue: [
      "fiction",
      "relationships",
      "emotional",
      "friendship",
      "healing",
    ],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-027",
    name: "Can we be stranger again",
    image: bookImages["can-we-be-strangers-again"],
    description:
      "Exploring the complexities of relationships and estrangement.",
    catalogue: [
      "romance",
      "fiction",
      "emotional",
      "relationships",
      "modern-romance",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-028",
    name: "Thank you for leaving",
    image: bookImages["thank-you-for-leaving"],
    description: "Finding strength and growth after heartbreak.",
    catalogue: [
      "self-help",
      "emotional",
      "healing",
      "breakup",
      "personal-growth",
    ],
    originalPrice: calculateOriginalPrice(119),
    discountedPrice: 119,
    size: "Paperback",
  },
  {
    id: "bk-029",
    name: "Too good to be true",
    image: bookImages["too-good-to-be-true"],
    description: "A suspenseful tale of deception and unexpected twists.",
    catalogue: ["thriller", "romance", "suspense", "mystery", "psychological"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-030",
    name: "I don't love you anymore",
    image: bookImages["i-dont-love-you-anymore"],
    description: "A deeply emotional journey of heartbreak and healing.",
    catalogue: ["romance", "emotional", "mental-health", "healing", "breakup"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-031",
    name: "Don't believe everything you think",
    image: bookImages["dont-believe-everything-you-think"],
    description: "Learn to quiet your mind and stop overthinking.",
    catalogue: [
      "mental-health",
      "self-help",
      "psychology",
      "mindfulness",
      "cbt",
    ],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-032",
    name: "Art of not overthinking",
    image: bookImages["art-of-not-overthinking"],
    description: "Practical tools to control anxious thoughts.",
    catalogue: [
      "self-help",
      "mental-health",
      "anxiety",
      "mindfulness",
      "wellness",
    ],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-033",
    name: "Art of laziness",
    image: bookImages["art-of-laziness"],
    description: "Embracing rest and finding productivity in stillness.",
    catalogue: [
      "self-help",
      "productivity",
      "wellness",
      "mindfulness",
      "philosophy",
    ],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-034",
    name: "Art of being alone",
    image: bookImages["art-of-being-alone"],
    description: "Embracing solitude as a path to self-growth.",
    catalogue: [
      "self-help",
      "philosophy",
      "mental-health",
      "solitude",
      "personal-growth",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-035",
    name: "Art of reading people's mind",
    image: bookImages["art-of-reading-mind"],
    description:
      "Understanding nonverbal cues and improving emotional intelligence.",
    catalogue: [
      "psychology",
      "self-help",
      "communication",
      "emotional-intelligence",
      "body-language",
    ],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
];
