// 👉 Change this path once if public structure changes
const BOOK_IMAGE_BASE_PATH = "/books";

export const bookImages = {
  "the-art-of-spending-money": `${BOOK_IMAGE_BASE_PATH}/the-art-of-spending-money.jpeg`,
  manifest: `${BOOK_IMAGE_BASE_PATH}/manifest.jpg`,
  "dont-sweat-the-small-stuff": `${BOOK_IMAGE_BASE_PATH}/dont-sweat-the-small-stuff.jpeg`,
  "letters-to-the-milena": `${BOOK_IMAGE_BASE_PATH}/letters-to-the-milena.jpeg`,
  "atomic-habits": `${BOOK_IMAGE_BASE_PATH}/atomic-habits.jpeg`,
  "psychology-of-money": `${BOOK_IMAGE_BASE_PATH}/psychology-of-money.jpeg`,
  "surrounded-by-idiots": `${BOOK_IMAGE_BASE_PATH}/surrounded-by-idiots.jpeg`,
  "palace-of-illusions": `${BOOK_IMAGE_BASE_PATH}/palace-of-illusions.jpeg`,
  "courage-to-be-disliked": `${BOOK_IMAGE_BASE_PATH}/courage-to-be-disliked.jpeg`,
  "subtle-art-not-giving-fck": `${BOOK_IMAGE_BASE_PATH}/subtle-art-not-giving-fck.jpeg`,
  "talking-with-psychopaths": `${BOOK_IMAGE_BASE_PATH}/talking-with-psychopaths.jpeg`,
  "laws-of-human-nature": `${BOOK_IMAGE_BASE_PATH}/laws-of-human-nature.jpeg`,
  "48-laws-of-power": `${BOOK_IMAGE_BASE_PATH}/48-laws-of-power.jpeg`,
  "diary-of-a-ceo": `${BOOK_IMAGE_BASE_PATH}/diary-of-a-ceo.jpeg`,
  "red-flags-and-rishtas": `${BOOK_IMAGE_BASE_PATH}/red-flags-and-rishtas.jpeg`,
  inmate: `${BOOK_IMAGE_BASE_PATH}/inmate.jpeg`,
  "housemaid-1": `${BOOK_IMAGE_BASE_PATH}/housemaid-1.jpeg`,
  "housemaid-2": `${BOOK_IMAGE_BASE_PATH}/housemaid-2.jpeg`,
  "housemaid-3": `${BOOK_IMAGE_BASE_PATH}/housemaid-3.jpeg`,
  "locked-door": `${BOOK_IMAGE_BASE_PATH}/locked-door.jpeg`,
  "never-lie": `${BOOK_IMAGE_BASE_PATH}/never-lie.jpeg`,
  "days-at-morisaki-1": `${BOOK_IMAGE_BASE_PATH}/days-at-morisaki-1.jpeg`,
  "days-at-morisaki-2": `${BOOK_IMAGE_BASE_PATH}/days-at-morisaki-2.jpeg`,
  "all-hell-ever-be": `${BOOK_IMAGE_BASE_PATH}/all-hell-ever-be.jpeg`,
  "was-i-ever-enough": `${BOOK_IMAGE_BASE_PATH}/was-i-ever-enough.jpeg`,
  "we-are-there-for-each-other": `${BOOK_IMAGE_BASE_PATH}/we-are-there-for-each-other.jpeg`,
  "can-we-be-strangers-again": `${BOOK_IMAGE_BASE_PATH}/can-we-be-strangers-again.jpeg`,
  "thank-you-for-leaving": `${BOOK_IMAGE_BASE_PATH}/thank-you-for-leaving.jpeg`,
  "too-good-to-be-true": `${BOOK_IMAGE_BASE_PATH}/too-good-to-be-true.jpeg`,
  "i-dont-love-you-anymore": `${BOOK_IMAGE_BASE_PATH}/i-dont-love-you-anymore.jpeg`,
  "dont-believe-everything-you-think": `${BOOK_IMAGE_BASE_PATH}/dont-believe-everything-you-think.png`,
  "art-of-not-overthinking": `${BOOK_IMAGE_BASE_PATH}/art-of-not-overthinking.jpeg`,
  "art-of-laziness": `${BOOK_IMAGE_BASE_PATH}/art-of-laziness.png`,
  "art-of-being-alone": `${BOOK_IMAGE_BASE_PATH}/art-of-being-alone.png`,
  "art-of-reading-mind": `${BOOK_IMAGE_BASE_PATH}/art-of-reading-mind.png`,
};
