import { bookImages } from "./bookImages";

// Helper function to calculate original price based on discounted price
// Rounds to nearest value that's 30-80% higher than discounted price
const calculateOriginalPrice = (discountedPrice) => {
  const minMultiplier = 1.3;
  const maxMultiplier = 1.8;
  const randomMultiplier =
    minMultiplier + Math.random() * (maxMultiplier - minMultiplier);
  const calculatedPrice = Math.round(discountedPrice * randomMultiplier);
  // Round to nearest 10 for cleaner pricing
  return Math.round(calculatedPrice / 10) * 10;
};

export const books = [
  {
    id: "bk-001",
    name: "The art of spending money",
    image: bookImages["the-art-of-spending-money"],
    description:
      "A practical guide to building a healthier relationship with money and spending intentionally.",
    catalogue: ["finance", "self-help", "trending"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-002",
    name: "Manifest",
    image: bookImages["manifest"],
    description:
      "A mindset-shifting book focused on belief systems and manifestation.",
    catalogue: ["self-help", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-003",
    name: "Don't smell the small stuff",
    image: bookImages["dont-sweat-the-small-stuff"],
    description: "Simple practices to reduce stress and live a calmer life.",
    catalogue: ["self-help", "trending"],
    originalPrice: calculateOriginalPrice(119),
    discountedPrice: 119,
    size: "Paperback",
  },
  {
    id: "bk-004",
    name: "Letter to millennia",
    image: bookImages["letters-to-the-milena"],
    description: "Reflections on modern struggles, ambition, and purpose.",
    catalogue: ["self-help", "philosophy"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-005",
    name: "Atomic habits",
    image: bookImages["atomic-habits"],
    description: "Build good habits and break bad ones with small changes.",
    catalogue: ["self-help", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-006",
    name: "Psychology money",
    image: bookImages["psychology-of-money"],
    description: "Timeless lessons on money, greed, and happiness.",
    catalogue: ["finance", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-007",
    name: "Surrounded by idiots",
    image: bookImages["surrounded-by-idiots"],
    description: "Understand personality types and improve communication.",
    catalogue: ["self-help", "bestseller", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-008",
    name: "Palace of illusions",
    image: bookImages["palace-of-illusions"],
    description: "A retelling of the Mahabharata from Draupadi's perspective.",
    catalogue: ["fiction", "novel", "mythology", "history", "trending"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-009",
    name: "Courage to be disliked",
    image: bookImages["courage-to-be-disliked"],
    description: "A philosophy-driven guide to personal freedom.",
    catalogue: ["philosophy", "self-help", "trending", "psychology"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-010",
    name: "The subtle art of not giving a f*ck",
    image: bookImages["subtle-art-not-giving-fck"],
    description: "A counterintuitive approach to living a good life.",
    catalogue: ["self-help", "psychology"],
    originalPrice: calculateOriginalPrice(119),
    discountedPrice: 119,
    size: "Paperback",
  },
  {
    id: "bk-011",
    name: "Talking with psychopaths",
    image: bookImages["talking-with-psychopaths"],
    description: "Insights into the minds of psychopaths and their behavior.",
    catalogue: ["psychology", "trending"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-012",
    name: "Law of human nature",
    image: bookImages["laws-of-human-nature"],
    description: "Understanding the forces that shape human behavior.",
    catalogue: ["psychology", "self-help", "bestseller", "trending"],
    originalPrice: calculateOriginalPrice(239),
    discountedPrice: 239,
    size: "Hardcover",
  },
  {
    id: "bk-013",
    name: "48 laws of power",
    image: bookImages["48-laws-of-power"],
    description: "Classic guide to power dynamics and strategy.",
    catalogue: ["self-help", "psychology", "trending", "bestseller"],
    originalPrice: calculateOriginalPrice(239),
    discountedPrice: 239,
    size: "Hardcover",
  },
  {
    id: "bk-014",
    name: "Diary of a CEO",
    image: bookImages["diary-of-a-ceo"],
    description: "Insights and lessons from a successful CEO's journey.",
    catalogue: ["business", "self-help"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-015",
    name: "Red flags and rishtas",
    image: bookImages["red-flags-and-rishtas"],
    description:
      "Navigating modern relationships and identifying warning signs.",
    catalogue: ["romance", "self-help", "trending"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-016",
    name: "Inmate",
    image: bookImages["inmate"],
    description: "A gripping psychological thriller full of twists.",
    catalogue: ["thriller", "novel", "trending", "mystery"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-017",
    name: "Housemaid 1",
    image: bookImages["housemaid-1"],
    description: "A dark psychological thriller with shocking revelations.",
    catalogue: ["thriller", "novel", "trending", "mystery"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-018",
    name: "Housemaid 2",
    image: bookImages["housemaid-2"],
    description: "The suspense continues with deeper secrets.",
    catalogue: ["thriller", "novel", "trending", "mystery"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-019",
    name: "Housemaid 3",
    image: bookImages["housemaid-3"],
    description: "A shocking conclusion to the Housemaid series.",
    catalogue: ["thriller", "novel", "trending", "mystery"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-020",
    name: "Locked door",
    image: bookImages["locked-door"],
    description: "A suspenseful thriller about secrets behind closed doors.",
    catalogue: ["thriller", "novel", "trending", "mystery"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-021",
    name: "Never lie",
    image: bookImages["never-lie"],
    description: "A psychological thriller about truth and deception.",
    catalogue: ["thriller", "novel", "trending", "mystery"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-022",
    name: "Days at morisaki shop 1",
    image: bookImages["days-at-morisaki-1"],
    description: "A heartwarming story about life and second chances.",
    catalogue: ["fiction", "trending", "japanese-literature"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-023",
    name: "Days at morisaki shop 2",
    image: bookImages["days-at-morisaki-2"],
    description: "Continuing the heartwarming journey at Morisaki shop.",
    catalogue: ["fiction", "japanese-literature", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-024",
    name: "All he'll be ever",
    image: bookImages["all-hell-ever-be"],
    description: "A deep exploration of relationships and expectations.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(229),
    discountedPrice: 229,
    size: "Paperback",
  },
  {
    id: "bk-025",
    name: "Was I ever enough",
    image: bookImages["was-i-ever-enough"],
    description: "A poignant reflection on self-worth and validation.",
    catalogue: ["self-help", "romance"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-026",
    name: "We are there for each other",
    image: bookImages["we-are-there-for-each-other"],
    description: "A story of friendship, support, and human connection.",
    catalogue: ["romance", "friendship", "trending"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-027",
    name: "Can we be stranger again",
    image: bookImages["can-we-be-strangers-again"],
    description:
      "Exploring the complexities of relationships and estrangement.",
    catalogue: ["romance", "fiction", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-028",
    name: "Thank you for leaving",
    image: bookImages["thank-you-for-leaving"],
    description: "Finding strength and growth after heartbreak.",
    catalogue: ["self-help", "romance", "trending"],
    originalPrice: calculateOriginalPrice(119),
    discountedPrice: 119,
    size: "Paperback",
  },
  {
    id: "bk-029",
    name: "Too good to be true",
    image: bookImages["too-good-to-be-true"],
    description: "A suspenseful tale of deception and unexpected twists.",
    catalogue: ["trending", "romance"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-030",
    name: "I don't love you anymore",
    image: bookImages["i-dont-love-you-anymore"],
    description: "A deeply emotional journey of heartbreak and healing.",
    catalogue: ["romance", "trending"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-031",
    name: "Don't believe everything you think",
    image: bookImages["dont-believe-everything-you-think"],
    description: "Learn to quiet your mind and stop overthinking.",
    catalogue: ["self-help", "psychology", "trending"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-032",
    name: "Art of not overthinking",
    image: bookImages["art-of-not-overthinking"],
    description: "Practical tools to control anxious thoughts.",
    catalogue: ["self-help", "trending"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-033",
    name: "Art of laziness",
    image: bookImages["art-of-laziness"],
    description: "Embracing rest and finding productivity in stillness.",
    catalogue: ["self-help", "trending"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-034",
    name: "Art of being alone",
    image: bookImages["art-of-being-alone"],
    description: "Embracing solitude as a path to self-growth.",
    catalogue: ["self-help", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-035",
    name: "Art of reading people's mind",
    image: bookImages["art-of-reading-mind"],
    description:
      "Understanding nonverbal cues and improving emotional intelligence.",
    catalogue: ["self-help", "trending"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-036",
    name: "5 Types of Wealth",
    image: bookImages["5-types-of-wealth"],
    description: "A practical guide to building wealth beyond money.",
    catalogue: ["finance", "self-help"],
    originalPrice: calculateOriginalPrice(189),
    discountedPrice: 189,
    size: "Paperback",
  },
  {
    id: "bk-037",
    name: "The Let Them Theory",
    image: bookImages["the-let-them-theory"],
    description: "Learning emotional freedom by letting go of control.",
    catalogue: ["self-help", "psychology"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-038",
    name: "The First 90 Days",
    image: bookImages["the-first-90-days"],
    description: "Proven strategies for career transitions and success.",
    catalogue: ["bestseller", "self-help"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-039",
    name: "Life’s Amazing Secret",
    image: bookImages["lifes-amazing-secret"],
    description: "A story-driven approach to happiness and success.",
    catalogue: ["self-help", "spirituality"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-040",
    name: "Energize Your Mind",
    image: bookImages["energize-you-mind"],
    description: "Unlock mental energy and peak performance.",
    catalogue: ["self-help", "psychology"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-041",
    name: "The Kite Runner",
    image: bookImages["kite-runner"],
    description: "A powerful story of friendship, guilt, and redemption.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(159),
    discountedPrice: 159,
    size: "Paperback",
  },
  {
    id: "bk-042",
    name: "A Thousand Splendid Suns",
    image: bookImages["thousand-splendid-suns"],
    description: "An emotional tale of love, loss, and resilience.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(159),
    discountedPrice: 159,
    size: "Paperback",
  },
  {
    id: "bk-043",
    name: "And the Mountains Echoed",
    image: bookImages["and-the-mountain-echoed"],
    description: "An interconnected family saga across generations.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-044",
    name: "The Mountain Is You",
    image: bookImages["the-mountain-is-you"],
    description: "Transforming self-sabotage into self-mastery.",
    catalogue: ["self-help", "psychology"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-045",
    name: "Before the Coffee Gets Cold 1",
    image: bookImages["before-the-coffee-gets-cold-1"],
    description: "A magical café where time travel is possible.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-046",
    name: "Tales from the cafe",
    image: bookImages["before-the-coffee-gets-cold-2"],
    description: "More heartwarming stories from the time-travel café.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-047",
    name: "Before your memory fades",
    image: bookImages["before-the-coffee-gets-cold-3"],
    description: "Emotional journeys across time and choices.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-048",
    name: "Before we say goodbye",
    image: bookImages["before-the-coffee-gets-cold-4"],
    description: "Exploring regret, hope, and second chances.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-049",
    name: "Before we forget kindness",
    image: bookImages["before-the-coffee-gets-cold-5"],
    description: "The continuation of the beloved time café stories.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-050",
    name: "Twisted Love",
    image: bookImages["twisted-love"],
    description: "A dark romance filled with obsession and secrets.",
    catalogue: ["romance", "thriller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-051",
    name: "Twisted Game",
    image: bookImages["twisted-game"],
    description: "A dangerous game of love, power, and betrayal.",
    catalogue: ["romance", "thriller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-052",
    name: "Twisted Hate",
    image: bookImages["twisted-hate"],
    description: "When hate turns into an irresistible attraction.",
    catalogue: ["romance", "thriller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-053",
    name: "Twisted Lies",
    image: bookImages["twisted-lies"],
    description: "A romance built on secrets, deception, and desire.",
    catalogue: ["romance", "thriller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-054",
    name: "King of Wrath",
    image: bookImages["king-of-wrath"],
    description: "A fiery romance driven by power and vengeance.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-055",
    name: "King of Pride",
    image: bookImages["king-of-pride"],
    description: "A passionate story of love and stubborn hearts.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-056",
    name: "King of Greed",
    image: bookImages["king-of-greed"],
    description: "When ambition and love collide in unexpected ways.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(159),
    discountedPrice: 159,
    size: "Paperback",
  },
  {
    id: "bk-057",
    name: "King of Sloth",
    image: bookImages["king-of-sloth"],
    description: "A slow-burning romance with emotional depth.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(159),
    discountedPrice: 159,
    size: "Paperback",
  },
  {
    id: "bk-058",
    name: "The God of Small Things",
    image: bookImages["god-of-small-things"],
    description: "A literary masterpiece about love, loss, and society.",
    catalogue: ["bestseller", "fiction"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-059",
    name: "Forest of Enhancement",
    image: bookImages["forest-of-enhancement"],
    description: "A thrilling fantasy adventure of growth and power.",
    catalogue: ["bestseller", "fiction"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-060",
    name: "The Last Queen",
    image: bookImages["last-queen"],
    description: "A dramatic tale set in a rich historical backdrop.",
    catalogue: ["history", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-061",
    name: "Ugly Love",
    image: bookImages["ugly-love"],
    description: "An emotional romance about pain, healing, and love.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-062",
    name: "A Little Life",
    image: bookImages["little-life"],
    description: "A deeply moving story of friendship and trauma.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(329),
    discountedPrice: 329,
    size: "Paperback",
  },
  {
    id: "bk-063",
    name: "Dark Matter",
    image: bookImages["dark-matter"],
    description: "A mind-bending sci-fi thriller about parallel lives.",
    catalogue: ["mystery", "thriller", "bestseller", "trending"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-064",
    name: "Verity",
    image: bookImages["varity"],
    description: "A psychological thriller full of shocking twists.",
    catalogue: ["mystery", "thriller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-065",
    name: "Zero to One",
    image: bookImages["zero-to-one"],
    description: "Insights on building groundbreaking startups.",
    catalogue: ["business", "entrepreneurship"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-066",
    name: "The $100 Startup",
    image: bookImages["100-dollar-startup"],
    description: "Turn small ideas into profitable businesses.",
    catalogue: ["business", "entrepreneurship"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-067",
    name: "The Lean Startup",
    image: bookImages["lean-startup"],
    description: "Build startups using continuous innovation.",
    catalogue: ["business", "entrepreneurship", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-068",
    name: "The Hard Thing About Hard Things",
    image: bookImages["hard-things-about-hard-things"],
    description: "Real-world lessons on building and managing companies.",
    catalogue: ["business", "entrepreneurship", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-069",
    name: "Blue Ocean Strategy",
    image: bookImages["blue-ocean-strategy"],
    description:
      "Create uncontested market space and make competition irrelevant.",
    catalogue: ["business", "entrepreneurship", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-070",
    name: "Ram Sita Raavan",
    image: bookImages["ram-sita-raavan"],
    description: "An epic retelling of mythology from multiple perspectives.",
    catalogue: ["mythology", "fiction"],
    originalPrice: calculateOriginalPrice(499),
    discountedPrice: 499,
    size: "Paperback",
  },
  {
    id: "bk-071",
    name: "Ram",
    image: bookImages["ram"],
    description: "The story of righteousness, duty, and leadership.",
    catalogue: ["mythology"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-072",
    name: "Sita",
    image: bookImages["sita"],
    description: "A powerful portrayal of strength, courage, and resilience.",
    catalogue: ["mythology"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-073",
    name: "Raavan",
    image: bookImages["ravaan"],
    description: "A misunderstood anti-hero from Indian mythology.",
    catalogue: ["mythology"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-074",
    name: "Meluha, Nagas & Vayaputra",
    image: bookImages["meluha-nagas-vayaputra"],
    description: "The complete Shiva Trilogy collection.",
    catalogue: ["mythology", "fiction"],
    originalPrice: calculateOriginalPrice(499),
    discountedPrice: 499,
    size: "Paperback",
  },
  {
    id: "bk-075",
    name: "Meluha",
    image: bookImages["meluha"],
    description: "The rise of Shiva and the beginning of a legend.",
    catalogue: ["mythology"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-076",
    name: "Nagas",
    image: bookImages["nagas"],
    description: "A tale of loyalty, mystery, and hidden warriors.",
    catalogue: ["mythology"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-077",
    name: "Vayaputra",
    image: bookImages["vayaputra"],
    description: "The final battle and the destiny of Shiva.",
    catalogue: ["mythology"],
    originalPrice: calculateOriginalPrice(229),
    discountedPrice: 229,
    size: "Paperback",
  },
  {
    id: "bk-078",
    name: "Mahagatha",
    image: bookImages["mahagatha"],
    description: "Ancient Indian stories that shape philosophical thought.",
    catalogue: ["mythology", "philosophy"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-079",
    name: "Naga Warrior",
    image: bookImages["naga-warrior"],
    description: "A fierce mythological fantasy of power and honor.",
    catalogue: ["mythology"],
    originalPrice: calculateOriginalPrice(159),
    discountedPrice: 159,
    size: "Paperback",
  },
  {
    id: "bk-080",
    name: "The Gita",
    image: bookImages["gita"],
    description: "Timeless spiritual wisdom on life and duty.",
    catalogue: ["spirituality", "philosophy"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-081",
    name: "Myth = Mythya",
    image: bookImages["myth-mythya"],
    description: "Reinterpreting mythology through modern perspectives.",
    catalogue: ["mythology", "fiction"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-082",
    name: "Bhagvat Gita",
    image: bookImages["bhagvat-gita"],
    description: "A sacred text exploring karma, devotion, and wisdom.",
    catalogue: ["spirituality", "philosophy"],
    originalPrice: calculateOriginalPrice(279),
    discountedPrice: 279,
    size: "Paperback",
  },
  {
    id: "bk-083",
    name: "The Hidden Hindu",
    image: bookImages["hidden-hindu"],
    description: "A thrilling blend of mythology and modern fiction.",
    catalogue: ["mythology", "fiction"],
    originalPrice: calculateOriginalPrice(419),
    discountedPrice: 419,
    size: "Paperback",
  },
  {
    id: "bk-084",
    name: "Mahabharat Unraveled",
    image: bookImages["mahabhrat-unraveled"],
    description: "Decoding the epic with historical insights.",
    catalogue: ["mythology", "history"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-085",
    name: "Ramayan Unraveled",
    image: bookImages["ramayan-unraveled"],
    description: "Exploring the Ramayan beyond the legends.",
    catalogue: ["mythology", "history"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-086",
    name: "The Metamorphosis",
    image: bookImages["the-metamorphosis"],
    description: "A haunting classic on alienation and identity.",
    catalogue: ["fiction", "classic"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-087",
    name: "The Trial",
    image: bookImages["the-trial"],
    description: "A chilling exploration of justice and bureaucracy.",
    catalogue: ["fiction", "classic"],
    originalPrice: calculateOriginalPrice(119),
    discountedPrice: 119,
    size: "Paperback",
  },
  {
    id: "bk-088",
    name: "Notes from Underground",
    image: bookImages["notes-from-underground"],
    description: "A philosophical dive into human consciousness.",
    catalogue: ["fiction", "philosophy"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-089",
    name: "Crime and Punishment",
    image: bookImages["crime-and-punishment"],
    description:
      "A psychological classic exploring guilt, morality, and redemption.",
    catalogue: ["fiction", "classic"],
    originalPrice: calculateOriginalPrice(189),
    discountedPrice: 189,
    size: "Paperback",
  },
  {
    id: "bk-090",
    name: "White Nights",
    image: bookImages["white-nights"],
    description: "A tender story of love, loneliness, and fleeting dreams.",
    catalogue: ["fiction", "romance"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-091",
    name: "The Alchemist",
    image: bookImages["alchemist"],
    description:
      "A philosophical tale about destiny, dreams, and self-discovery.",
    catalogue: ["fiction", "philosophy"],
    originalPrice: calculateOriginalPrice(99),
    discountedPrice: 99,
    size: "Paperback",
  },
  {
    id: "bk-092",
    name: "Haunting Adeline",
    image: bookImages["haunting-adeline"],
    description: "A dark romantic thriller filled with obsession and suspense.",
    catalogue: ["horror", "thriller", "bestseller"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-093",
    name: "Hunting Adeline",
    image: bookImages["hunting-adeline"],
    description: "A gripping continuation of a dark and intense love story.",
    catalogue: ["horror", "thriller", "bestseller"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-094",
    name: "Pride and Prejudice",
    image: bookImages["pride-and-prejudice"],
    description:
      "A timeless romance exploring love, class, and misunderstandings.",
    catalogue: ["fiction", "classic"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-095",
    name: "Make Epic Money",
    image: bookImages["make-epic-money"],
    description:
      "A practical guide to building wealth with clarity and confidence.",
    catalogue: ["finance", "self-help"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-096",
    name: "Do Epic Shit",
    image: bookImages["do-epic-shit"],
    description: "Motivational insights to push beyond limits and take action.",
    catalogue: ["self-help", "bestseller", "trending"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-097",
    name: "Get Epic Shit Done",
    image: bookImages["get-epic-shit-done"],
    description: "Actionable strategies to boost productivity and focus.",
    catalogue: ["self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-098",
    name: "Dark Psychology",
    image: bookImages["dark-pyshcology"],
    description: "Understanding manipulation, influence, and human behavior.",
    catalogue: ["psychology", "self-help"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-099",
    name: "Red, White & Blue",
    image: bookImages["red-white-blue"],
    description:
      "A dramatic fictional narrative filled with emotion and depth.",
    catalogue: ["fiction", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-100",
    name: "Red Flag Rishtas",
    image: bookImages["red-flag-rishtas"],
    description: "Exploring modern relationships and emotional warning signs.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-101",
    name: "The Love Hypothesis",
    image: bookImages["love-hypothesis"],
    description: "A smart romantic comedy set in the world of academia.",
    catalogue: ["romance", "fiction"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-102",
    name: "Love from Laothe",
    image: bookImages["love-from-laothe"],
    description: "A heartfelt romance exploring distance and destiny.",
    catalogue: ["romance", "fiction"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-103",
    name: "Love, Theoretically",
    image: bookImages["love-theoretically"],
    description: "A contemporary romance blending science and emotions.",
    catalogue: ["romance", "fiction"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-104",
    name: "Icebreakers",
    image: bookImages["icebreakers"],
    description: "A fun, modern romance with charm and chemistry.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-105",
    name: "Wildfire",
    image: bookImages["wildfire"],
    description: "An emotional romance ignited by passion and conflict.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(159),
    discountedPrice: 159,
    size: "Paperback",
  },
  {
    id: "bk-106",
    name: "Family of Liars",
    image: bookImages["family-of-liars"],
    description: "A suspenseful mystery packed with secrets and twists.",
    catalogue: ["mystery", "thriller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-107",
    name: "Before the coffee gets cold set",
    image: bookImages["before-the-coffee-gets-cold-set"],
    description:
      "A collection of heartwarming magical realism stories about time, love, and connection.",
    catalogue: ["bestseller", "novel"],
    originalPrice: calculateOriginalPrice(599),
    discountedPrice: 599,
    size: "Paperback",
  },
  {
    id: "bk-108",
    name: "Jujutsu set 1 - 21",
    image: bookImages["jujutsu-set-1-21"],
    description:
      "Complete collection of the popular dark fantasy manga series.",
    catalogue: ["manga", "set", "novel"],
    originalPrice: calculateOriginalPrice(2229),
    discountedPrice: 2229,
    size: "Paperback",
  },
  {
    id: "bk-109",
    name: "Harry porter set 1 - 7",
    image: bookImages["harry-porter-set-1-7"],
    description:
      "The complete magical journey of the boy wizard in a collector's set.",
    catalogue: ["thriller", "set", "novel"],
    originalPrice: calculateOriginalPrice(1399),
    discountedPrice: 1399,
    size: "Paperback",
  },
  {
    id: "bk-110",
    name: "Agatha christie set",
    image: bookImages["agatha-christie-set"],
    description: "Classic mystery collection from the queen of crime fiction.",
    catalogue: ["mystery", "set", "novel"],
    originalPrice: calculateOriginalPrice(699),
    discountedPrice: 699,
    size: "Paperback",
  },
  {
    id: "bk-111",
    name: "Dark verse set",
    image: bookImages["dark-verse-set"],
    description:
      "A gripping collection of dark romance and psychological thrillers.",
    catalogue: ["thriller", "set", "novel"],
    originalPrice: calculateOriginalPrice(649),
    discountedPrice: 649,
    size: "Paperback",
  },
  {
    id: "bk-112",
    name: "Good girl guides to murder set",
    image: bookImages["good-girl-guides-to-murder-set"],
    description:
      "Complete YA mystery trilogy with thrilling investigations and twists.",
    catalogue: ["mystery", "set", "novel"],
    originalPrice: calculateOriginalPrice(479),
    discountedPrice: 479,
    size: "Paperback",
  },
  {
    id: "bk-113",
    name: "King of wrath set",
    image: bookImages["king-of-wrath-set"],
    description:
      "A complete contemporary romance series filled with passion and drama.",
    catalogue: ["romance", "set"],
    originalPrice: calculateOriginalPrice(649),
    discountedPrice: 649,
    size: "Paperback",
  },
  {
    id: "bk-114",
    name: "Twisted love series set",
    image: bookImages["twisted-love-series-set"],
    description:
      "Complete dark romance collection exploring complex relationships and secrets.",
    catalogue: ["romance", "set"],
    originalPrice: calculateOriginalPrice(649),
    discountedPrice: 649,
    size: "Paperback",
  },
  {
    id: "bk-115",
    name: "Meluha nagas vayaputra set",
    image: bookImages["meluha-nagas-vayaputra-set"],
    description: "Complete mythological fiction series based on Indian epics.",
    catalogue: ["mythology", "set"],
    originalPrice: calculateOriginalPrice(499),
    discountedPrice: 499,
    size: "Paperback",
  },
  {
    id: "bk-116",
    name: "Chainsawman set",
    image: bookImages["chainsawman-set"],
    description:
      "Complete action-packed manga series with horror and supernatural elements.",
    catalogue: ["manga", "set"],
    originalPrice: calculateOriginalPrice(2499),
    discountedPrice: 2499,
    size: "Paperback",
  },
  {
    id: "bk-117",
    name: "Diary of a whimpy kid set",
    image: bookImages["diary-of-a-whimpy-kid-set"],
    description:
      "Complete collection of hilarious middle-grade stories and comics.",
    catalogue: ["stories", "set"],
    originalPrice: calculateOriginalPrice(1799),
    discountedPrice: 1799,
    size: "Paperback",
  },
  {
    id: "bk-118",
    name: "Lord of the rings set",
    image: bookImages["lord-of-the-rings-set"],
    description: "Epic fantasy trilogy in a beautiful collector's edition.",
    catalogue: ["fiction", "set"],
    originalPrice: calculateOriginalPrice(449),
    discountedPrice: 449,
    size: "Paperback",
  },
  {
    id: "bk-119",
    name: "Hunger games set",
    image: bookImages["hunger-games-set"],
    description:
      "Complete dystopian trilogy of survival, revolution, and hope.",
    catalogue: ["thriller", "set"],
    originalPrice: calculateOriginalPrice(649),
    discountedPrice: 649,
    size: "Paperback",
  },
  {
    id: "bk-120",
    name: "Good girl guides to murder",
    image: bookImages["good-girl-guides-to-murder"],
    description:
      "A teen detective investigates a murder in her small town in this gripping YA mystery.",
    catalogue: ["mystery", "suspense", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-121",
    name: "Good girl bad blood",
    image: bookImages["good-girl-bad-blood"],
    description:
      "The sequel where Pip finds herself in another chilling investigation with personal stakes.",
    catalogue: ["mystery", "suspense", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-122",
    name: "As good as dead",
    image: bookImages["as-good-as-dead"],
    description:
      "The final installment in the trilogy where Pip faces her most dangerous adversary yet.",
    catalogue: ["mystery", "suspense", "bestseller"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-123",
    name: "7 husbands of evelyn hugo",
    image: bookImages["7-husbands-of-evelyn-hugo"],
    description:
      "A legendary film star reveals the truth about her glamorous life and seven marriages.",
    catalogue: ["romance", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-124",
    name: "And Then There Were None",
    image: bookImages["and-then-there-were-none"],
    description:
      "Ten strangers trapped on an island are murdered one by one in this classic mystery.",
    catalogue: ["thriller", "crime", "mystery"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-125",
    name: "The Murder of Roger Ackroyd",
    image: bookImages["the-murder-of-roger-ackroyd"],
    description:
      "Hercule Poirot investigates the murder of a wealthy man in a village full of secrets.",
    catalogue: ["thriller", "crime", "mystery"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-126",
    name: "Murder on the Orient Express",
    image: bookImages["murder-on-the-orient-express"],
    description:
      "A murder occurs on a snowbound train, and Poirot must find the killer among the passengers.",
    catalogue: ["thriller", "crime", "mystery"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-127",
    name: "Death on the Nile",
    image: bookImages["death-on-the-nile"],
    description:
      "A luxurious Nile cruise turns deadly, and Poirot must solve a seemingly impossible murder.",
    catalogue: ["thriller", "crime", "mystery"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-128",
    name: "The A.B.C. Murders",
    image: bookImages["the-a-b-c-murders"],
    description:
      "Poirot races against time to stop a serial killer who murders in alphabetical order.",
    catalogue: ["thriller", "crime", "mystery"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-129",
    name: "A Murder Is Announced",
    image: bookImages["a-murder-is-announced"],
    description:
      "Miss Marple investigates when a murder is advertised in the local newspaper before it happens.",
    catalogue: ["thriller", "crime", "mystery"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-130",
    name: "Almanack of naval ravikant",
    image: bookImages["almanack-of-naval-ravikant"],
    description:
      "A guide to wealth, happiness, and life wisdom from entrepreneur and philosopher Naval Ravikant.",
    catalogue: ["finance", "self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-131",
    name: "Crucial conversation : A high stake book",
    image: bookImages["crucial-conversation-a-high-stake-book"],
    description:
      "Tools for talking when stakes are high, opinions vary, and emotions run strong.",
    catalogue: ["self-help", "researched"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-132",
    name: "Breaking the habit of being yourself",
    image: bookImages["breaking-the-habit-of-being-yourself"],
    description:
      "How to rewire your brain and create a new personality through neuroscience and quantum physics.",
    catalogue: ["self-help", "researched"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-133",
    name: "Everything i know about love",
    image: bookImages["everything-i-know-about-love"],
    description:
      "A heartfelt memoir about friendship, love, and figuring out life in your twenties.",
    catalogue: ["romance"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-134",
    name: "Becoming supernatural",
    image: bookImages["becoming-supernatural"],
    description:
      "How common people are doing the uncommon to transform their health, wealth, and happiness.",
    catalogue: ["self-help", "researched"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-135",
    name: "You are the placebo",
    image: bookImages["you-are-the-placebo"],
    description:
      "Making your mind matter through the power of belief and consciousness.",
    catalogue: ["researched", "self-help"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-136",
    name: "Thinking fast and slow",
    image: bookImages["thinking-fast-and-slow"],
    description:
      "Nobel winner Daniel Kahneman explores the two systems that drive how we think.",
    catalogue: ["researched", "self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-137",
    name: "Hidden hindu 1",
    image: bookImages["hidden-hindu-1"],
    description:
      "A mythological thriller exploring ancient secrets and divine mysteries.",
    catalogue: ["mythology", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-138",
    name: "Hidden hindu 2",
    image: bookImages["hidden-hindu-2"],
    description:
      "The second installment in the epic mythological adventure series.",
    catalogue: ["mythology", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-139",
    name: "Hidden hindu 3",
    image: bookImages["hidden-hindu-3"],
    description:
      "The thrilling conclusion to the mythological adventure trilogy.",
    catalogue: ["mythology", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-140",
    name: "The secret book",
    image: bookImages["the-secret-book"],
    description: "The groundbreaking book that reveals the law of attraction.",
    catalogue: ["self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-141",
    name: "The magic book",
    image: bookImages["the-magic-book"],
    description:
      "Discover the magic in everyday life through gratitude and positive thinking.",
    catalogue: ["self-help"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-142",
    name: "The power book",
    image: bookImages["the-power-book"],
    description: "Unleash the power within you to create the life you desire.",
    catalogue: ["self-help"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-143",
    name: "No excuse",
    image: bookImages["no-excuse"],
    description:
      "A powerful guide to taking responsibility and achieving your goals.",
    catalogue: ["self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-144",
    name: "Influence : The psychology of persuasion",
    image: bookImages["influence-the-psychology-of-persuasion"],
    description:
      "The classic guide to persuasion and understanding psychological triggers.",
    catalogue: ["self-help"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-145",
    name: "Silent patient",
    image: bookImages["silent-patient"],
    description:
      "A psychological thriller about a woman who shoots her husband and then stops speaking.",
    catalogue: ["mystery", "novel", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-146",
    name: "Can't hurt me",
    image: bookImages["cant-hurt-me"],
    description:
      "David Goggins' inspirational story of transforming pain into power.",
    catalogue: ["self-help"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-147",
    name: "Master your emotions",
    image: bookImages["master-your-emotions"],
    description:
      "A practical guide to understanding and controlling your emotional state.",
    catalogue: ["self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-148",
    name: "Make time",
    image: bookImages["make-time"],
    description:
      "How to focus on what matters every day in a world full of distractions.",
    catalogue: ["self-help"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-149",
    name: "The courage to be disliked",
    image: bookImages["the-courage-to-be-disliked"],
    description:
      "A Japanese phenomenon about finding happiness through Adlerian psychology.",
    catalogue: ["self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-150",
    name: "The courage to be happy",
    image: bookImages["the-courage-to-be-happy"],
    description:
      "The sequel that continues the journey toward true happiness and fulfillment.",
    catalogue: ["self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-151",
    name: "Mindset",
    image: bookImages["mindset"],
    description:
      "How we can learn to fulfill our potential through the power of our beliefs.",
    catalogue: ["self-help", "bestseller"],
    originalPrice: calculateOriginalPrice(139),
    discountedPrice: 139,
    size: "Paperback",
  },
  {
    id: "bk-152",
    name: "Kafka on the Shore",
    image: bookImages["kafka-on-the-shore"],
    description:
      "A mind-bending novel that intertwines two remarkable characters in magical realism.",
    catalogue: ["novel", "bestseller"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-153",
    name: "Norwegian Wood",
    image: bookImages["norwegian-wood"],
    description:
      "A nostalgic story of loss and burgeoning sexuality set in 1960s Tokyo.",
    catalogue: ["novel", "bestseller"],
    originalPrice: calculateOriginalPrice(159),
    discountedPrice: 159,
    size: "Paperback",
  },
  {
    id: "bk-154",
    name: "Sputnik Sweetheart",
    image: bookImages["sputnik-sweetheart"],
    description:
      "A haunting story of unrequited love and mysterious disappearance.",
    catalogue: ["novel"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-155",
    name: "Men Without Women",
    image: bookImages["men-without-women"],
    description:
      "A collection of seven stories about men who find themselves alone.",
    catalogue: ["novel"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-156",
    name: "My friends",
    image: bookImages["my-friends"],
    description:
      "A compelling narrative about friendship, loyalty, and life's unexpected turns.",
    catalogue: ["novel"],
    originalPrice: calculateOriginalPrice(189),
    discountedPrice: 189,
    size: "Paperback",
  },
  {
    id: "bk-157",
    name: "Anxious people",
    image: bookImages["anxious-people"],
    description:
      "A poignant comedy about a hostage drama that reveals our shared humanity.",
    catalogue: ["novel", "bestseller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-158",
    name: "Mossad",
    image: bookImages["mossad"],
    description:
      "The secret history of Israel's intelligence agency and its most daring missions.",
    catalogue: ["thriller", "bestseller"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-159",
    name: "Commando",
    image: bookImages["commando"],
    description:
      "Gripping real-life stories of bravery and sacrifice from military operations.",
    catalogue: ["thriller"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-160",
    name: "You've reached sam",
    image: bookImages["you-ve-reached-sam"],
    description:
      "A heartfelt YA novel about grief, love, and letting go after a tragic loss.",
    catalogue: ["romance", "novel", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-161",
    name: "Ignited minds by apj",
    image: bookImages["ignite-minds-apj"],
    description:
      "Dr. APJ Abdul Kalam's vision for empowering India's youth through education.",
    catalogue: ["self-help", "biography", "bestseller"],
    originalPrice: calculateOriginalPrice(129),
    discountedPrice: 129,
    size: "Paperback",
  },
  {
    id: "bk-162",
    name: "Elon musk biography",
    image: bookImages["elon-mush-biography"],
    description:
      "The definitive biography of the visionary entrepreneur reshaping our world.",
    catalogue: ["biography", "bestseller"],
    originalPrice: calculateOriginalPrice(199),
    discountedPrice: 199,
    size: "Paperback",
  },
  {
    id: "bk-163",
    name: "Lean in",
    image: bookImages["lean-in"],
    description:
      "Sheryl Sandberg's groundbreaking book on women, work, and leadership.",
    catalogue: ["biography"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-164",
    name: "The design of everyday thing",
    image: bookImages["the-design-of-everyday-thing"],
    description:
      "A classic guide to human-centered design and creating user-friendly products.",
    catalogue: ["self-help"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-165",
    name: "Men from mars and women from venus",
    image: bookImages["men-from-mars-and-women-from-venus"],
    description:
      "The classic guide to understanding the opposite sex and improving relationships.",
    catalogue: ["novel"],
    originalPrice: calculateOriginalPrice(179),
    discountedPrice: 179,
    size: "Paperback",
  },
  {
    id: "bk-166",
    name: "Guest list",
    image: bookImages["guest-list"],
    description:
      "A wedding celebration turns deadly in this gripping locked-room mystery.",
    catalogue: ["thriller", "suspense", "mystery"],
    originalPrice: calculateOriginalPrice(169),
    discountedPrice: 169,
    size: "Paperback",
  },
  {
    id: "bk-167",
    name: "The one thing",
    image: bookImages["the-one-thing"],
    description:
      "The surprisingly simple truth behind extraordinary results in work and life.",
    catalogue: ["self-help", "bestseller", "bestseller"],
    originalPrice: calculateOriginalPrice(149),
    discountedPrice: 149,
    size: "Paperback",
  },
  {
    id: "bk-168",
    name: "Why we sleep",
    image: bookImages["why-we-sleep"],
    description:
      "Unlocking the power of sleep and dreams for a healthier, safer, and smarter life.",
    catalogue: ["researched"],
    originalPrice: calculateOriginalPrice(189),
    discountedPrice: 189,
    size: "Paperback",
  },
];
