// utils/reviews.js - 20 reviews with SEO-optimized filenames
export const reviewsData = [
  {
    id: "review-1",
    reviewerName: "Priya Sharma",
    reviewerImage:
      "/review/reviewers/priya-sharma-5-star-review-the-art-of-clarity.jpeg",
    rating: 5,
    comment:
      "Murthy Thevar's 'The Art of Clarity' completely transformed my thinking! The practical exercises helped me overcome indecision. A must-read for anyone feeling stuck.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 15, 2026",
    verified: true,
    helpful: 127,
  },
  {
    id: "review-2",
    reviewerName: "Rajesh Kumar",
    reviewerImage:
      "/review/reviewers/rajesh-kumar-5-star-clarity-framework-review.jpeg",
    rating: 5,
    comment:
      "Finally, a self-help book that delivers! Murthy Thevar's clarity framework is simple yet powerful. Highly recommended!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 12, 2026",
    verified: true,
    helpful: 89,
  },
  {
    id: "review-3",
    reviewerName: "Anita Desai",
    reviewerImage:
      "/review/reviewers/anita-desai-business-owner-clarity-book-review.jpeg",
    rating: 5,
    comment:
      "As a business owner, this book helped me make better decisions. Should be on every entrepreneur's shelf.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 10, 2026",
    verified: true,
    helpful: 156,
  },
  {
    id: "review-4",
    reviewerName: "Neha Gupta",
    reviewerImage:
      "/review/reviewers/neha-gupta-anxiety-relief-clarity-exercises-review.jpeg",
    rating: 5,
    comment:
      "The clarity exercises helped me reduce anxiety and make better life choices. Stands out among self-help books.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 5, 2026",
    verified: true,
    helpful: 203,
  },
  {
    id: "review-5",
    reviewerName: "Amit Patel",
    reviewerImage:
      "/review/reviewers/amit-patel-mental-fog-clarity-book-review.jpeg",
    rating: 5,
    comment:
      "Helped me clear mental fog and focus on what truly matters. A treasure trove of wisdom.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 3, 2026",
    verified: true,
    helpful: 112,
  },
  {
    id: "review-6",
    reviewerName: "Deepak Joshi",
    reviewerImage:
      "/review/reviewers/deepak-joshi-student-career-clarity-book-review.jpeg",
    rating: 5,
    comment:
      "As a student struggling with career clarity, this book provided the framework I needed. My go-to recommendation.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 18, 2026",
    verified: true,
    helpful: 188,
  },
  {
    id: "review-7",
    reviewerName: "Meera Krishnamurthy",
    reviewerImage:
      "/review/reviewers/meera-krishnamurthy-wisdom-psychology-book-review.jpeg",
    rating: 5,
    comment:
      "Combines ancient wisdom with modern psychology. Every chapter offers valuable insights. A masterpiece!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 20, 2026",
    verified: true,
    helpful: 167,
  },
  {
    id: "review-8",
    reviewerName: "Shweta Malhotra",
    reviewerImage:
      "/review/reviewers/shweta-malhotra-professional-life-clarity-review.jpeg",
    rating: 5,
    comment:
      "Profound yet practical insights. Helped me find direction in personal and professional life.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 22, 2026",
    verified: true,
    helpful: 134,
  },
  {
    id: "review-9",
    reviewerName: "Sanjay Verma",
    reviewerImage:
      "/review/reviewers/sanjay-verma-decision-making-book-review.jpeg",
    rating: 5,
    comment:
      "A clear roadmap to better thinking and decision-making. Worth every rupee.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 14, 2026",
    verified: true,
    helpful: 92,
  },
  {
    id: "review-10",
    reviewerName: "Pooja Bhatia",
    reviewerImage:
      "/review/reviewers/pooja-bhatia-relationship-clarity-review.jpeg",
    rating: 5,
    comment:
      "Helped me break free from mental blocks and achieve clarity in relationships and career.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 9, 2026",
    verified: true,
    helpful: 176,
  },
  {
    id: "review-11",
    reviewerName: "Lakshmi Iyer",
    reviewerImage:
      "/review/reviewers/lakshmi-iyer-life-changing-book-review.jpeg",
    rating: 5,
    comment:
      "Practical, insightful, and life-changing. Already recommended to 10 friends!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 7, 2026",
    verified: true,
    helpful: 219,
  },
  {
    id: "review-12",
    reviewerName: "Anjali Kapoor",
    reviewerImage:
      "/review/reviewers/anjali-kapoor-mental-peace-clarity-book-review.jpeg",
    rating: 5,
    comment:
      "Found mental peace and clarity during a difficult time. Forever grateful for this book.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 4, 2026",
    verified: true,
    helpful: 198,
  },
  {
    id: "review-13",
    reviewerName: "Karthik Rajan",
    reviewerImage:
      "/review/reviewers/karthik-rajan-clear-thinking-framework-review.jpeg",
    rating: 5,
    comment:
      "Practical framework for clear thinking transformed how I approach problems.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 2, 2026",
    verified: true,
    helpful: 154,
  },
  {
    id: "review-14",
    reviewerName: "Vikram Singh",
    reviewerImage:
      "/review/reviewers/vikram-singh-actionable-self-help-book-review.jpeg",
    rating: 4,
    comment:
      "Practical, actionable, and life-changing. One of the best investments I've made.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 8, 2026",
    verified: true,
    helpful: 67,
  },
  {
    id: "review-15",
    reviewerName: "Rahul Mehta",
    reviewerImage:
      "/review/reviewers/rahul-mehta-engaging-clarity-tools-review.jpeg",
    rating: 4,
    comment: "Engaging and relatable. Offers practical tools that I use daily.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 11, 2026",
    verified: true,
    helpful: 94,
  },
  {
    id: "review-16",
    reviewerName: "Sneha Reddy",
    reviewerImage:
      "/review/reviewers/sneha-reddy-overcoming-analysis-paralysis-review.jpeg",
    rating: 5,
    comment:
      "This book helped me stop overthinking and start taking action. The clarity framework is revolutionary!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 17, 2026",
    verified: true,
    helpful: 145,
  },
  {
    id: "review-17",
    reviewerName: "Manoj Tiwari",
    reviewerImage:
      "/review/reviewers/manoj-tiwari-corporate-professional-book-review.jpeg",
    rating: 5,
    comment:
      "As a corporate professional, decision-making was always challenging. This book gave me the tools to think clearly under pressure.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 19, 2026",
    verified: true,
    helpful: 112,
  },
  {
    id: "review-18",
    reviewerName: "Kavita Singh",
    reviewerImage:
      "/review/reviewers/kavita-singh-mom-life-clarity-book-review.jpeg",
    rating: 5,
    comment:
      "Juggling work and family left me exhausted. This book helped me prioritize and find mental peace. Thank you Murthy Thevar!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 21, 2026",
    verified: true,
    helpful: 178,
  },
  {
    id: "review-19",
    reviewerName: "Arjun Nair",
    reviewerImage:
      "/review/reviewers/arjun-nair-startup-founder-clarity-review.jpeg",
    rating: 5,
    comment:
      "Every startup founder needs this book. Murthy Thevar's strategies helped me lead my team with clarity and confidence.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 23, 2026",
    verified: true,
    helpful: 203,
  },
  {
    id: "review-20",
    reviewerName: "Divya Sharma",
    reviewerImage:
      "/review/reviewers/divya-sharma-personal-growth-clarity-review.jpeg",
    rating: 5,
    comment:
      "Life-changing read! The Art of Clarity helped me identify my goals and take purposeful action. Highly recommend to everyone.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 24, 2026",
    verified: true,
    helpful: 156,
  },
  {
    id: "review-21",
    reviewerName: "Ananya Deshpande",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "Finally, a book that cuts through the noise! The Art of Clarity gave me practical tools to declutter my mind and focus on what truly matters. Every chapter felt like a therapy session.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 26, 2026",
    verified: true,
    helpful: 142,
  },
  {
    id: "review-22",
    reviewerName: "Rahul Mehta",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "Worth every rupee and every minute spent reading. I've gifted this book to three colleagues already. The frameworks for decision-making are simple yet powerful. Must-buy!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 27, 2026",
    verified: true,
    helpful: 198,
  },
  {
    id: "review-23",
    reviewerName: "Priya Nair",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "This book transformed my morning routine. I used to feel overwhelmed before noon; now I have crystal-clear priorities. The writing style is engaging and actionable. Highly recommended!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 28, 2026",
    verified: true,
    helpful: 167,
  },
  {
    id: "review-24",
    reviewerName: "Vikram Singh",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 4,
    comment:
      "One of the best self-help books I've read in recent years. The chapter on 'Clarity in Communication' alone is worth the price. My team meetings have become 10x more productive.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 29, 2026",
    verified: true,
    helpful: 123,
  },
  {
    id: "review-25",
    reviewerName: "Kavitha Iyer",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "I've struggled with anxiety and overthinking for years. This book didn't just motivate me—it gave me actual exercises to rewire my thinking. Life-changing doesn't even begin to describe it.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "April 30, 2026",
    verified: true,
    helpful: 234,
  },
  {
    id: "review-26",
    reviewerName: "Arjun Reddy",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "As an entrepreneur, decision fatigue was ruining my days. This book gave me a framework to make better decisions faster. My business partner is reading it now. Absolute gold!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 1, 2026",
    verified: true,
    helpful: 189,
  },
  {
    id: "review-27",
    reviewerName: "Neha Gupta",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "I bought this on a whim during TheBookX's ₹1 sale. Best decision ever! The practical exercises helped me quit my toxic job and start my own freelance business. Thank you, Murthy Thevar!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 2, 2026",
    verified: true,
    helpful: 312,
  },
  {
    id: "review-28",
    reviewerName: "Suresh Menon",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 4,
    comment:
      "Solid 4.5 stars! Some concepts are repeated but honestly, repetition helps retention. The real-life examples are relatable and the action steps are practical. Highly recommend for anyone feeling stuck.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 3, 2026",
    verified: true,
    helpful: 98,
  },
  {
    id: "review-29",
    reviewerName: "Meera Krishnamoorthy",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "Where has this book been all my life? The Art of Clarity helped me navigate a difficult career transition. I now have a clear roadmap for my future. Every young professional needs this.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 4, 2026",
    verified: true,
    helpful: 176,
  },
  {
    id: "review-30",
    reviewerName: "Karthik Balaji",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "I've read over 50 self-help books. This one stands out because it's not just theory—it's a practical manual. The 'Clarity Audit' exercise alone is worth re-reading the book for.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 5, 2026",
    verified: true,
    helpful: 145,
  },
  {
    id: "review-31",
    reviewerName: "Swati Choudhury",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "This book made me cry (in a good way). I realized I had been living everyone else's expectations. The Art of Clarity helped me rediscover my own voice. Forever grateful.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 6, 2026",
    verified: true,
    helpful: 267,
  },
  {
    id: "review-32",
    reviewerName: "Rajesh Khanna",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 4,
    comment:
      "Excellent read! I appreciated how the author used Indian examples and contexts. It made the concepts so much more relatable. TheBookX delivered it in pristine condition as always.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 7, 2026",
    verified: true,
    helpful: 112,
  },
  {
    id: "review-33",
    reviewerName: "Lakshmi Srinivasan",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "I've recommended this to my entire book club. We're doing a group re-read next month. The 'Weekly Clarity Review' has become a non-negotiable part of my Sundays. Absolute masterpiece!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 8, 2026",
    verified: true,
    helpful: 203,
  },
  {
    id: "review-34",
    reviewerName: "Aditya Patil",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "Stopped me from quitting my career impulsively. Instead, the clarity exercises helped me identify what was actually bothering me. I negotiated better work conditions and now I love my job again.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 9, 2026",
    verified: true,
    helpful: 158,
  },
  {
    id: "review-35",
    reviewerName: "Pooja Verma",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "The Art of Clarity + TheBookX's fast delivery = perfect combination. This book helped me declutter my home, my mind, and my relationships. My stress levels have dropped significantly.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 10, 2026",
    verified: true,
    helpful: 191,
  },
  {
    id: "review-36",
    reviewerName: "Ganesh Iyer",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 4,
    comment:
      "Very insightful! Some parts felt repetitive but the core message is powerful. The journal prompts helped me unlock answers I didn't know I had. Worth every paisa.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 11, 2026",
    verified: true,
    helpful: 87,
  },
  {
    id: "review-37",
    reviewerName: "Shreya Mahajan",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "This book should be taught in every school. The concepts of mental clarity and purposeful living are so simple yet profoundly missing in our education system. Every parent and teacher needs this.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 12, 2026",
    verified: true,
    helpful: 221,
  },
  {
    id: "review-38",
    reviewerName: "Nitin Bansal",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "I bought this for myself and ended up buying 5 more copies for my team. The productivity gains we've seen are measurable. Thank you, TheBookX, for stocking such quality reads at affordable prices!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 13, 2026",
    verified: true,
    helpful: 178,
  },
  {
    id: "review-39",
    reviewerName: "Anjali Nair",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "Hands down the most impactful book I read in 2025. I've highlighted almost every page. The clarity framework helped me start my own podcast and I've never been happier. Buy it. Read it. Live it.",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 14, 2026",
    verified: true,
    helpful: 289,
  },
  {
    id: "review-40",
    reviewerName: "Rohan Sharma",
    reviewerImage: "/review/reviewers/reviewer-fallback-image.jpeg",
    rating: 5,
    comment:
      "I was skeptical at first because I've read so many self-help books. But The Art of Clarity delivered. The '30-Day Clarity Challenge' at the end changed my life. My goals are clearer, my relationships are better, and my anxiety is gone. Thank you, Murthy Thevar and TheBookX!",
    bookId: "bk-002",
    bookName: "The Art of Clarity",
    authorName: "Murthy Thevar",
    date: "May 15, 2026",
    verified: true,
    helpful: 423,
  },
];

export const getReviewsByAuthor = (authorName) => {
  return reviewsData.filter((review) => review.authorName === authorName);
};

export const getReviewsByBook = (bookId) => {
  return reviewsData.filter((review) => review.bookId === bookId);
};

export const getAverageRating = (reviews) => {
  if (!reviews.length) return 0;
  const sum = reviews.reduce((acc, review) => acc + review.rating, 0);
  return (sum / reviews.length).toFixed(1);
};
